name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, turbo]

      - name: Build
        run: pnpm build && cd packages/sample-app && pnpm install

      - name: Check types
        run: pnpm typecheck

      - name: Check lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run examples
        run: pnpm test:examples

  docs:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8

      - name: Update README
        run: |
          cd packages/next-action && 
          pnpm install --ignore-scripts
          pnpm copy:readme

      - name: Build docs
        run: cd packages/next-action && pnpm build:docs

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/next-action/docs
